const { ethers } = require("ethers");

const {
  getProvider,
  getWebSocketProvider,
} = require("../../../blockchainService");
const { getTokenAddress } = require("../../../../config/tokenConfig");
const { creditConfirmedDeposit } = require("../../../depositCreditService");
const pool = require("../../../../config/db");

const provider = getProvider();
const wsProvider = getWebSocketProvider();
const TRANSFER_ABI = [
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "function decimals() view returns (uint8)",
];

const confirmations = Number(
  process.env.BLOCKCHAIN_CONFIRMATIONS || 3
);

const tokens = [
  {
    asset: "USDC",
    address: process.env.SEPOLIA_USDC_CONTRACT || null,
  },
  {
    asset: "USDT",
    address: process.env.SEPOLIA_USDT_CONTRACT || null,
  },
].filter((token) => token.address);

const tokenContracts = new Map();

for (const token of tokens) {
  tokenContracts.set(
    token.address.toLowerCase(),
    token.asset
  );
}

const iface = new ethers.Interface(TRANSFER_ABI);

const startEthereumDepositListener = async () => {
  if (tokens.length === 0) {
    throw new Error(
      "No Sepolia token contracts configured"
    );
  }

  console.log(
    `Ethereum deposit listener starting with ${tokens.length} token(s)`
  );

  for (const token of tokens) {
    const contract = new ethers.Contract(
      token.address,
      TRANSFER_ABI,
      provider
    );

    const decimals = await contract.decimals();

    console.log(
      `Listening for ${token.asset} deposits`,
      token.address,
      `decimals=${decimals}`
    );
  }

  const filter = {
    address: tokens.map((token) => token.address),
    topics: [
      ethers.id(
        "Transfer(address,address,uint256)"
      ),
    ],
  };

 wsProvider.on(filter, async (log) => {
    try {
      if (log.removed) {
        return;
      }

      const parsed = iface.parseLog({
        topics: log.topics,
        data: log.data,
      });

      if (!parsed) {
        return;
      }

      const fromAddress =
        parsed.args[0];

      const toAddress =
        parsed.args[1];

      const rawAmount =
        parsed.args[2];

      const tokenAddress =
        log.address.toLowerCase();

      const asset =
        tokenContracts.get(tokenAddress);

      if (!asset) {
        return;
      }

      // Only monitor addresses generated by StabiX
      const addressResult = await pool.query(
        `SELECT
           id,
           user_id,
           network,
           chain_id,
           address
         FROM deposit_addresses
         WHERE network = 'ethereum'
           AND status = 'active'
           AND LOWER(address) = LOWER($1)
         LIMIT 1`,
        [toAddress]
      );

      if (addressResult.rows.length === 0) {
        return;
      }

      const depositAddress =
        addressResult.rows[0];

      // Get token decimals
      const tokenContract =
        new ethers.Contract(
          tokenAddress,
          TRANSFER_ABI,
          provider
        );

      const decimals =
        await tokenContract.decimals();

      const amount =
        ethers.formatUnits(
          rawAmount,
          decimals
        );

      const blockNumber =
        log.blockNumber;

      const eventIndex =
        log.index;

      console.log(
        "ETHEREUM DEPOSIT DETECTED:",
        {
          asset,
          amount,
          txHash: log.transactionHash,
          to: toAddress,
          depositAddressId:
            depositAddress.id,
        }
      );

     // Find the deposit intent linked to this deposit address
const intentResult = await pool.query(
  `SELECT
     id,
     mode,
     network,
     chain_id,
     asset
   FROM deposit_intents
   WHERE deposit_address_id = $1
     AND asset = $2
     AND network = 'ethereum'
     AND mode = 'instant'
     AND status = 'pending'
   ORDER BY created_at DESC
   LIMIT 1`,
  [
    depositAddress.id,
    asset,
  ]
);

const depositIntent =
  intentResult.rows[0] || null;

if (!depositIntent) {
  console.log(
    "No pending deposit intent found for address:",
    depositAddress.id,
    "- recording blockchain deposit without intent"
  );
} else {
  console.log(
    "Deposit intent matched:",
    {
      intentId: depositIntent.id,
      mode: depositIntent.mode,
      network: depositIntent.network,
      chainId: depositIntent.chain_id,
    }
  );
}
// Store blockchain deposit.
// Unique constraint prevents duplicate events.
const insertResult = await pool.query(
  `INSERT INTO blockchain_deposits (
     network,
     chain_id,
     tx_hash,
     block_number,
     event_index,
     token_contract,
     from_address,
     to_address,
     amount,
     deposit_address_id,
     deposit_intent_id,
     status
   )
   VALUES (
     $1,
     $2,
     $3,
     $4,
     $5,
     $6,
     $7,
     $8,
     $9,
     $10,
     $11,
     'detected'
   )
   ON CONFLICT (
     network,
     tx_hash,
     event_index
   )
   DO NOTHING
   RETURNING id`,
 [
  depositIntent?.network || "ethereum",
  depositIntent?.chain_id || Number(process.env.ETHEREUM_CHAIN_ID),
  log.transactionHash,
  blockNumber,
  eventIndex,
  tokenAddress,
  fromAddress,
  toAddress,
  rawAmount.toString(),
  depositAddress.id,
  depositIntent?.id || null,
]
);

// Already processed
if (insertResult.rows.length === 0) {
  console.log(
    "Duplicate blockchain event ignored:",
    log.transactionHash,
    eventIndex
  );

  return;
}

      const blockchainDepositId =
        insertResult.rows[0].id;

      console.log(
        "Blockchain deposit recorded:",
        blockchainDepositId
      );

     if (depositIntent) {
  await pool.query(
    `UPDATE deposit_intents
     SET
       status = 'matched',
       updated_at = CURRENT_TIMESTAMP
     WHERE id = $1
       AND status = 'pending'`,
    [depositIntent.id]
  );

  console.log(
    "Deposit intent matched:",
    depositIntent.id
  );
}
      // Wait for required confirmations
      await provider.waitForTransaction(
        log.transactionHash,
        confirmations
      );

      // Mark as confirmed
      const confirmResult =
        await pool.query(
          `UPDATE blockchain_deposits
           SET
             status = 'confirmed',
             confirmed_at = CURRENT_TIMESTAMP
           WHERE id = $1
             AND status = 'detected'
           RETURNING id`,
          [blockchainDepositId]
        );

      if (confirmResult.rows.length === 0) {
        return;
      }

      console.log(
        "Blockchain deposit confirmed:",
        blockchainDepositId
      );

      // Credit StabiX wallet
     const creditResult = await creditConfirmedDeposit({
  blockchainDepositId,
  asset,
  amount,
  fromAddress,
});

      console.log(
        "DEPOSIT CREDITED:",
        creditResult
      );
    } catch (err) {
      console.error(
        "ETHEREUM DEPOSIT LISTENER ERROR:",
        err
      );
    }
  });

  console.log(
    "ETHEREUM deposit listener is ACTIVE"
  );
};

module.exports = {
  startEthereumDepositListener,
};